[target.armv7-unknown-linux-musleabihf]
rustflags = [
    "-C", "target-cpu=cortex-a9",
    "-C", "target-feature=+neon,+vfp3,+d32,+dsp",
    "-C", "opt-level=3",
    "-C", "inline-threshold=100",
    "-C", "lto=fat",
    "-C", "codegen-units=1"
]
